# Iterative seating algorithm

## General Idea
The algorithm picks a random set of guests for one table and compares it with another random set. The set with a higher "closeness" score is kept and then compared to new random sets until a better one is found. The algorithm runs for a predefined number of iterations per table. The final set for the first table is then removed from the guest matrix and the seating function runs again for the next table. This continues until all guests are seated.

## Open issues
  - How to save data? -> IDEA: save initial dataframe use result indices to derive guests from headers and delete for each table similar to the guest matrix
  - last iteration unnessecary -> IF attending / seats_per_table == 1 : seat everyone at the last table w/o iteration
  - increase performance by decreasing iterations? -> assumption: it's more likely to find better results quicker when fewer seats are available
  - How to write seating for one table as a function to then be called within the tables loop
  - rename variables for better readability (consistent indices, rename arr_bin to arr etc.), maybe indexed table variable -> https://stackoverflow.com/questions/13603215/using-a-loop-in-python-to-name-variables

In [2]:
# import libraries
import pandas as pd
import numpy as np


# read in test data and transform into an np array for later calculations
guest_matrix =np.array(pd.read_csv("../../data/test_guest.csv", sep=";",usecols= [1,2,3,4,5,6,7,8,9,10]))

# initial values for number of people, seats per table, iterations
attending = 10
seats_per_table = 5
iters = 50

#def seating_iterative(attending, seats_per_table, iters, guest_matrix):
 
while attending > 0:  
    # create binary numpy array with given values
    arr_bin = np.array([1]*seats_per_table + [0]*(attending - seats_per_table) )

    # for testing only
    np.random.shuffle(arr_bin)
    
    # initialise best fit and best array for comparison
    arr_best = np.array(arr_bin)
    fit_best = guest_matrix.dot(arr_best).dot(arr_best)

    # while loop for seating iteratively 
    i = 0
    while i < iters:
        np.random.shuffle(arr_bin)
        fit_new = guest_matrix.dot(arr_bin).dot(arr_bin)

        if fit_new > fit_best:
            arr_best = np.array(arr_bin)
            fit_best = fit_new
    #print statement for testing only
        print (arr_best, "; ", fit_best, "; ",arr_bin, "; ",fit_new)
        i += 1

    # determine indices of rows to be deleted
    # maybe improve by using the np.where function -> see transformation of input
    get_indexes = lambda arr_best, xs: [j for (y, j) in zip(xs, range(len(xs))) if arr_best == y]
    i_del = get_indexes(1,arr_best)
    print(i_del)

    # deleting seated guests from guest matrix
    guest_matrix = np.delete(guest_matrix, i_del, 0)
    guest_matrix = np.delete(guest_matrix, i_del, 1)
    print(guest_matrix)
    
    tablenumber = i + 1
    table_id = "table " + tablenumber
    seating = pd.DataFrame()
    
    seating[table_id] = guestlist.loc(i_del, "fullname")
    
    # minimise attending
    attending -= seats_per_table

    
    
# calling seating algorithm until all guests are seated
#while attending > 0:
    

[0 0 1 1 1 1 0 1 0 0] ;  5200 ;  [0 0 1 1 1 1 0 1 0 0] ;  5200
[0 0 1 1 1 1 0 1 0 0] ;  5200 ;  [1 0 1 1 0 0 1 0 1 0] ;  1600
[1 1 0 0 1 0 1 0 0 1] ;  5600 ;  [1 1 0 0 1 0 1 0 0 1] ;  5600
[1 1 0 0 1 0 1 0 0 1] ;  5600 ;  [0 1 0 1 1 0 0 1 0 1] ;  1600
[1 1 0 0 1 0 1 0 0 1] ;  5600 ;  [0 1 0 0 1 1 0 1 0 1] ;  1200
[1 1 0 0 1 0 1 0 0 1] ;  5600 ;  [0 1 0 0 0 0 1 1 1 1] ;  5600
[1 1 0 0 1 0 1 0 0 1] ;  5600 ;  [1 0 0 1 1 1 0 0 0 1] ;  1200
[1 1 1 0 0 0 0 0 1 1] ;  8800 ;  [1 1 1 0 0 0 0 0 1 1] ;  8800
[1 1 1 0 0 0 0 0 1 1] ;  8800 ;  [1 0 1 0 1 1 0 0 0 1] ;  4800
[1 1 1 0 0 0 0 0 1 1] ;  8800 ;  [0 1 0 1 0 1 1 0 1 0] ;  5200
[1 1 1 0 0 0 0 0 1 1] ;  8800 ;  [0 1 0 0 1 0 1 0 1 1] ;  5600
[1 1 1 0 0 0 0 0 1 1] ;  8800 ;  [0 1 0 1 1 0 0 0 1 1] ;  5200
[1 1 1 0 0 0 0 0 1 1] ;  8800 ;  [0 1 0 1 1 0 0 0 1 1] ;  5200
[1 1 1 0 0 0 0 0 1 1] ;  8800 ;  [0 0 1 1 0 1 1 1 0 0] ;  4800
[1 1 1 0 0 0 0 0 1 1] ;  8800 ;  [0 1 0 0 1 1 1 0 1 0] ;  5600
[1 1 1 0 0 0 0 0 1 1] ;  8800 ;  [1 0 1 0 0 1 0 0 1 1] 